Add file on continuous integration to the Quickstart
Infectious-Disease-Modeling-Hubs/hubDocs pull request #113
Opened 2024-04-22 16:56 UTC by mmkerr

Resolve issue #110 by adding file on continuous integration to the Quickstart (after 'uploading and validating config files').

2024-04-24 12:48 UTC, annakrystalli requested changes
Overall, almost there! Just a couple of minor corrections requested.

2024-04-24 12:48 UTC, annakrystalli commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +remotes::install_github("Infectious-Disease-Modeling-Hubs/hubValidations")
```suggestion
remotes::install_github("Infectious-Disease-Modeling-Hubs/hubCI")
```

2024-04-24 12:48 UTC, annakrystalli commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +If your hub is hosted on GitHub, you can download GitHub Actions using the command `use_hub_github_action()` with the name of the action in parentheses.
Again I think this needs to be clarified in that, if their hub is hosted on GitHub they can ***make use*** of our GitHub Actions. Anyone in an Rstudio project can download our actions

2024-04-25 02:14 UTC, nickreich approved these changes
I am good with this as is, once @annakrystalli 's comments are addressed. thanks for addressing the comments I left in the Google Doc version of this!

2024-04-25 16:34 UTC, mmkerr commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +remotes::install_github("Infectious-Disease-Modeling-Hubs/hubValidations")
Done!

2024-04-25 16:37 UTC, mmkerr commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +If your hub is hosted on GitHub, you can download GitHub Actions using the command `use_hub_github_action()` with the name of the action in parentheses.
@annakrystalli I have now highlighted this information in this section. In addition, the first paragraph also contains a sentence indicating that hubs must be hosted on GitHub to use GitHub Actions.

2024-04-29 13:45 UTC, annakrystalli commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +Continuous integration (CI) is a practice that involves automating the way code and data are validated prior to being merged into a shared repository. This allows code and data to be built and tested
```suggestion
Continuous integration (CI) is a practice that involves automating the way code and data are validated prior to being merged into a shared repository. This allows code and data to be built and tested when any changes are made, which can help users and developers identify and debug errors sooner. CI tasks are carried out via a *workflow*, an automated process with steps (i.e., *jobs*) that are run either sequentially or simultaneously. Workflows are triggered by an *event*, or a specific activity within a repository, such as a request to merge new code or data into a branch of a repository. Hubs that are hosted on GitHub with hubverse-compliant structure can use [GitHub Actions](https://github.com/features/actions), and specifically the hubverse GitHub Action templates we've developed to perform a variety of CI workflows. 
```

2024-04-29 14:07 UTC, annakrystalli approved these changes
All good from me

2024-04-29 14:10 UTC, merged