Add Sample-output-type page
Infectious-Disease-Modeling-Hubs/hubDocs pull request #118
Opened 2024-05-22 20:43 UTC by mzorn-58

2024-05-28 18:50 UTC, nickreich commented on docs/source/overview/contact.md
> -- For any problems with our software or tools, please [file an issue](#file_issues) in the appropriate repository.
I note a lot of changes like this where anchor links are changed from e.g. `(#file_issues)` to `(#file-issues)`. Why are these changes being made? 

In general, I would suggest making these kinds of changes separate from the main PR, as they are solving a different issue than the main/titular issue in this PR about sample data. It makes it easier to review/merge several smaller PRs.

2024-05-28 18:53 UTC, nickreich commented on docs/source/overview/contact.md
> -- For any problems with our software or tools, please [file an issue](#file_issues) in the appropriate repository.
Were the old links broken and this is fixing them? or is this bringing us into compliance with some style guidelines?

2024-05-28 18:56 UTC, nickreich commented on docs/source/user-guide/model-output.md
> +More details about sample-output-type can be found in [sample-output-type](../user-guide/sample-output-type.md).
Can we make the name of the link more explanatory here. E.g. replace "[sample-output-type]" with "[the page describing sample output type data]"

2024-05-28 18:56 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | location | output_type| Output_type_id | value |
field names should be lowercase

2024-05-28 18:57 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +{origin_date: “2024-03-15”, horizon: “-1”, location: “MA”}<br>
these quotes could be in type-writer text to indicate a "code block"

2024-05-28 18:57 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | location | output_type| Output_type_id | value |
this applies to other tables lower down as well.

2024-05-28 18:58 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 100,
spacing is wrong for this line, which needs to be indented more.

2024-05-28 19:00 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +In words, the above configuration specifies that samples are required, they must be integers, and there must be exactly (i.e., no more or less than) 100 samples per modeling task.
We should clarify that the above words are describing the "output_type_id_params" specification, and that the "value" specifications correspond to the values contained in the "value" column (e..g they must be storable as numeric "double" format and be no less than zero).

2024-05-28 19:02 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
needs indentation

2024-05-28 19:05 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +
Could we add a caption-like comment saying something like, "rows are shaded to indicate different samples for the same compound forecast task. For example, the first two rows correspond to the same modeling task but they are highlighted to show that the first row is from sample "s0" while the second row is from sample "s1".

2024-05-28 19:06 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
indendtation

2024-05-28 19:08 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +**Submission B**: sample output_type where a compound modeling task corresponds to a combination of values for origin_date, horizon, and location. In this example, **the proportions of all four varia
same comment as above, could we say something like "once again, rows are grouped by so that each unique sample for each modeling task is together. Therefore, the first four rows correspond to the first sample ("s0") for the first modeling task and the second four rows correspond to the second sample ("s1") for the first modeling task."

2024-05-28 19:08 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
indentation

2024-05-28 19:09 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
indentation

2024-05-28 19:11 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +<li>Both Submissions B and C would pass validation since when the data are grouped by the “compound_taskid_set” variables you can always find a group of rows that have the same output_type_id.</li>
for these lists, can we use the native markdown lists, with just 
```
text here

- some text with a dash in front
- a second bullet
```
rather than the current <li> tags?

2024-05-28 19:12 UTC, nickreich commented on docs/source/user-guide/sample-output-type.md
> +<li>Both Submissions B and C would pass validation since when the data are grouped by the “compound_taskid_set” variables you can always find a group of rows that have the same output_type_id.</li>
also applies to the lists below.

2024-05-28 19:12 UTC, nickreich requested changes
See comments throughout - I think in general the translation of the google doc content looks good, but some comments about formatting and some requested additions. Thank you!

2024-05-28 21:35 UTC, micokoch commented on docs/source/overview/contact.md
> -- For any problems with our software or tools, please [file an issue](#file_issues) in the appropriate repository.
Sorry - this is my fault! In reviewing the new page Martha created I saw that the use of underscores and hyphens in place of spaces was inconsistent throughout hubDocs, and decided to establish a uniform style. The first pages that I believe Anna created, all used hyphens, and a few pages I reviewed (e.g., [this Google Developer page](https://developers.google.com/style/filenames)) suggested hyphens should be used instead of underscores. I think all the other small edits/changes made were me cleaning the code in different places. Anyway, sorry I didn't make a separate PR - I got carried away and I sometimes forget what branch/fork I'm working on.

2024-05-29 01:35 UTC, nickreich commented on docs/source/overview/contact.md
> -- For any problems with our software or tools, please [file an issue](#file_issues) in the appropriate repository.
All good! This is helpful detail about the changes, and I appreciate the drive to standardize. These details could be submitted as a note with the PR as well, to justify the changes. Maybe we could put in the hubDocs README (under contribution guidelines?) or some other place some of these stylistic guidelines that we are following?

2024-05-29 15:45 UTC, mzorn-58 commented on docs/source/user-guide/model-output.md
> +More details about sample-output-type can be found in [sample-output-type](../user-guide/sample-output-type.md).
change made

2024-05-29 15:47 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | location | output_type| Output_type_id | value |
done

2024-05-29 15:55 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +{origin_date: “2024-03-15”, horizon: “-1”, location: “MA”}<br>
done

2024-05-29 15:56 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 100,
indentation added

2024-05-29 16:34 UTC, micokoch commented
In addition to adding the sample-output-type page, this PR is standardizing the use of hyphens in place of spaces for file, directory, and link names, instead of using underscores. An explanation and further details can be found in the README file. A couple of small link fixes were also included in this PR (to make sure they could be compiled and built locally without errors or warnings).

2024-05-29 16:35 UTC, micokoch commented on docs/source/overview/contact.md
> -- For any problems with our software or tools, please [file an issue](#file_issues) in the appropriate repository.
Hi Nick, I put the changes in the README where you suggested, as it seemed like the most reasonable place. I also added a comment to the PR where I explain and justify some of the other changes made. Thanks for reviewing.

2024-05-29 17:35 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +In words, the above configuration specifies that samples are required, they must be integers, and there must be exactly (i.e., no more or less than) 100 samples per modeling task.
done

2024-05-29 17:36 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
indented

2024-05-29 19:39 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +
done

2024-05-29 19:46 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
done

2024-05-29 19:52 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +**Submission B**: sample output_type where a compound modeling task corresponds to a combination of values for origin_date, horizon, and location. In this example, **the proportions of all four varia
done

2024-05-29 19:53 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
done

2024-05-29 19:55 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
done

2024-05-29 19:59 UTC, mzorn-58 commented on docs/source/user-guide/sample-output-type.md
> +<li>Both Submissions B and C would pass validation since when the data are grouped by the “compound_taskid_set” variables you can always find a group of rows that have the same output_type_id.</li>
changed both

2024-06-05 15:13 UTC, nickreich approved these changes

2024-06-05 15:13 UTC, merged