Attempt at fixing issue #115
Infectious-Disease-Modeling-Hubs/hubDocs pull request #122
Opened 2024-06-05 18:56 UTC by micokoch

Hello,
This PR was trying to address issue #115 . As I mentioned in the issue, I used the HubEnsembles manuscript verbiage to explain the model output and maintain consistency. @elray1 - could you look at this PR and see if it can be approved / needs changes / needs to be discarded.

As a side note, I'm having issues because my fork keeps falling behind, and some of the new changes are incompatible, and it has been a bit of a nightmare to sync my fork and branches.
Thank you!

2024-06-05 19:32 UTC, lshandross requested changes

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/model-output.md
> +Hubs should specify the collection of task id variables for which samples are expected to capture dependence; e.g., the first option listed above might specify that samples should be drawn from distr
Is there a reason why there's extra whitespace at the end of the line here and on line 64?

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | location | output_type| Output_type_id | value |
Is there a reason that `Origin_Date` and `Output_type_id` are capitalized?

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date | horizon | location | output_type| Output_type_id | value |
Again, Origin_Date and Output_type_id are capitalized here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 100,
Fix the indentation here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | variant |location | output_type| Output_type_id | value |
Again, Origin_Date and Output_type_id are capitalized here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Fix indentation here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Again, Origin_Date and Output_type_id are capitalized here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> -Rows are shaded to indicate different samples for the same compound forecast task. For example in the table below, the first two rows correspond to the same modeling task but they are highlighted to
Is there a reason this part was removed? It seems like it may be helpful to the reader

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Fix indentation here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Fix indentation here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Again, Origin_Date and Output_type_id are capitalized here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Fix indentation here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Again, Origin_Date and Output_type_id are capitalized here

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +<li>validation that all of the proportions in a set of “mean” output_types sum to 1.</li>
```suggestion
<li>validate that all of the proportions in a set of “mean” output_types sum to 1.</li>
```

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> + - validation that all of the proportions in a set of “mean” output_types sum to 1.
```suggestion
 - validate that all of the proportions in a set of “mean” output_types sum to 1.
```

2024-06-05 19:32 UTC, lshandross commented on docs/source/user-guide/sample-output-type.md
> +Documentation about tests for other output types can be found in  [Validation Pull Requests on GitHub](https://infectious-disease-modeling-hubs.github.io/hubValidations/articles/validate-pr.html#vali
```suggestion
Documentation about tests for other output types can be found in [Validation Pull Requests on GitHub](https://infectious-disease-modeling-hubs.github.io/hubValidations/articles/validate-pr.html#validate_pr-check-details).  
```

2024-06-06 20:20 UTC, micokoch commented on docs/source/user-guide/model-output.md
> +Hubs should specify the collection of task id variables for which samples are expected to capture dependence; e.g., the first option listed above might specify that samples should be drawn from distr
When I remember, I try to leave to white spaces after every line, because it ensures there is a line break before the next line. It's usually not necessary, but also serves as a marker that there should be a line break.

2024-06-06 20:36 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | location | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved now.

2024-06-06 20:36 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date | horizon | location | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:36 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 100,
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:36 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +| Origin_date | horizon | variant |location | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:37 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:37 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:37 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +<li>validation that all of the proportions in a set of “mean” output_types sum to 1.</li>
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:38 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> + - validation that all of the proportions in a set of “mean” output_types sum to 1.
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:38 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +Documentation about tests for other output types can be found in  [Validation Pull Requests on GitHub](https://infectious-disease-modeling-hubs.github.io/hubValidations/articles/validate-pr.html#vali
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:38 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:38 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:38 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> -Rows are shaded to indicate different samples for the same compound forecast task. For example in the table below, the first two rows correspond to the same modeling task but they are highlighted to
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:39 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:39 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +"min_samples_per_task": 90,
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:39 UTC, micokoch commented on docs/source/user-guide/sample-output-type.md
> +|compound_idx| Origin_date |location | horizon | variant | output_type| Output_type_id | value |
Hi @lshandross - thanks for reviewing this so carefully. As far as I can tell, all those edits on `sample-output-type` were mistakes made when I tried to update my fork and so forth. What I did was just copy the newest official version of `sample-output-type` and replace it with my old copy. So all these issues should be solved.

2024-06-06 20:41 UTC, micokoch commented
Hi @lshandross - thanks for the review. Sorry I made you review a problematic version of `sample-output-type`. I messed up when I was updating my fork and I didn't even realize I had kept that old version of the file. I just deleted my version and updated it with the current, accepted one - so that should all be fixed. Thanks!

2024-06-06 20:42 UTC, micokoch commented
Hello. I am removing @nickreich as a reviewer, since he reviewed this previously and I made the change he asked for (removing the journal title).

2024-06-06 20:50 UTC, lshandross approved these changes

2024-06-06 20:50 UTC, lshandross commented on docs/source/user-guide/model-output.md
> +Hubs should specify the collection of task id variables for which samples are expected to capture dependence; e.g., the first option listed above might specify that samples should be drawn from distr
Linting rules generally seem to prefer no whitespace at the end of lines, though I'm not sure what the rules are for non-code files. Since there's already a new line below, the whitespace probably isn't necessary, but I don't have a strong opinion on this. I'll approve the changes for now since I don't have any other comments.

2024-06-09 01:31 UTC, elray1 approved these changes

2024-06-09 10:51 UTC, merged