How to become member of hubverse@groups.io
Infectious-Disease-Modeling-Hubs/hubDocs pull request #79
Opened 2023-11-30 16:27 UTC by mzorn-58

2023-11-30 16:30 UTC, mzorn-58 commented
@nickreich @micokoch easy review needed. Thanks!

2023-11-30 17:25 UTC, nickreich commented on docs/source/overview/contribute.md
> -(file_issues)=
I see this anchoring link is removed. are we sure that it is not linked to elsewhere in the hubdocs?

2023-11-30 17:27 UTC, nickreich requested changes
one small comment on this file. Also, it seems like there is a contribute.md file that is in the root directory that should be deleted?

2023-11-30 17:54 UTC, mzorn-58 commented on docs/source/overview/contribute.md
> -(file_issues)=
@nickreich anchoring link added back in.

2024-01-08 22:31 UTC, mzorn-58 commented
@nickreich can you merge this?

2024-01-09 03:52 UTC, nickreich approved these changes
i made small changes for markdown and it looks good.

2024-01-09 03:52 UTC, merged