Code color in dark/light, email & Issue #82
Infectious-Disease-Modeling-Hubs/hubDocs pull request #84
Opened 2024-01-11 23:48 UTC by micokoch

2024-01-18 14:50 UTC, nickreich requested changes
I suggest not making the email change. The colors seem ok.

2024-01-18 14:50 UTC, nickreich commented on docs/source/overview/contact.md
> +- To reach out directly, please send a message to <a href="mailto:mzorn@umass.edu">the group owner</a>.
I think we should leave this as the more generic hubverse+owner email. otherwise we'll have to rememeber to update this when Martha leaves, etc...

2024-01-18 14:50 UTC, nickreich commented on docs/_static/css/custom.css
> +html[data-theme="light"] {
These colors seem fine to me. I will note that the logo colors are here, in case there is a way to thematically choose colors here or elsewhere on the site. 

Blue - HEX #3C88BE; R(60), G(136), B(190); C-76, M-37, Y-8, K-0
Light Blue - HEX #7AC6F4; R(122), G(198), B(244); C-53, M-7, Y-0, K-0

2024-01-18 14:50 UTC, nickreich commented on docs/source/overview/contact.md
> +- To reach out directly, please send a message to <a href="mailto:mzorn@umass.edu">the group owner</a>.
For example, as least I receive emails sent to that above address, possibly others too.

2024-01-18 20:33 UTC, micokoch commented on docs/source/overview/contact.md
> +- To reach out directly, please send a message to <a href="mailto:mzorn@umass.edu">the group owner</a>.
Hi Nick. I wasn't sure if anyone checked the "group owner" email. I changed all references to Martha's email to go to the "group owner" email.

2024-01-18 20:37 UTC, micokoch commented on docs/_static/css/custom.css
> +html[data-theme="light"] {
I can change all colors (I think), but since there are only two colors in this palette, it makes sense to limit them to very specific uses. Since I only set default colors for 3 things (using custom css), I decided to use them for those three uses:
1. I used the blue for image borders.
2. I used the blue for `code` in the light mode.
3. I used the light blue for `code` in the dark mode.
The downside to this is that the blues resemble hyperlinked text, so I can revert if you prefer.

2024-01-19 02:03 UTC, nickreich approved these changes
All looks good to me!

2024-01-19 02:03 UTC, merged